### ISSUE TITLE
Love your theme

### ISSUE THREAD

**Issue by enzime4u** [JesseKuntz/ocean-code#1]
Hi , 
I love your theme a lot , is gonna get updated ? 

did you consider making a iterm2 version and also a slack theme [?[](url)](https://slackthemes.net/#/aubergine)

Thank you

**Comment by JesseKuntz** [comment]
Hey! So glad that you like it! Regarding updating it, is there something in specific that you are looking for?

I probably will not make an iTerm2 version - currently using something that's customized the way I like it but doesn't really look anything like the VSCode theme.

Making the Slack theme seems interesting though, I'll take a look at that soon 😃

**Comment by JesseKuntz** [comment]
@enzime4u made some changes to the README, and added a bonus section talking about what I use for iTerm2: https://github.com/JesseKuntz/ocean-code/blob/master/README.md#bonus-themes. Let me know what you think!

Edit: put together a Slack one as well, since it wasn't too hard.

**Comment by enzime4u** [comment]
> Hey! So glad that you like it! Regarding updating it, is there something in specific that you are looking for?
> 
> I probably will not make an iTerm2 version - currently using something that's customized the way I like it but doesn't really look anything like the VSCode theme.
> 
> Making the Slack theme seems interesting though, I'll take a look at that soon 😃

Thank you for the time to answer to me , maybe make some different variants of the theme , I found the Night Shift [https://github.com/Jean-Tinland/vscode-theme-desaturated](url) theme synthax very good to be implemented into Ocean Code . Those are just my thoughts :)
